ARG JAVA_VERSION=__JAVA_VERSION__
FROM eclipse-temurin:${JAVA_VERSION}-jdk AS builder
WORKDIR /app
COPY . .
RUN chmod +x gradlew && ./gradlew clean bootJar --no-daemon -x test

FROM eclipse-temurin:${JAVA_VERSION}-jdk
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
